---
  - name: Print os facts
    hosts: all
    tasks:
      - name: Print OS
        debug:
          msg: "{{ ansible_distribution }}"
      - name: Print fact
        debug:
          msg: "{{ some_fact }}"
  - name: Playbook для Fedora хостов
    hosts: fedora
    tasks:
      - name: Показать значение переменной fedora_custom_var
        debug:
          msg: "Значение переменной: {{ fedora_custom_var }}"
